### ISSUE TITLE
Use on Gitlab

### ISSUE THREAD

**Issue by brdjns-zz** [BradleyA/markit#26]
Have you considered adapting your script for pushing to Gitlab repositories? I know many devs have migrated there from here after the recent news of the MSFT acquisition.

**Comment by BradleyA** [comment]
No I have not considered adapting it to GitLab, since I am not a GitLab user.  Off the top of my head it may require very little if any code changes.  The script would need to change the help text from GitHub to GitHub or GitLab.  I would need a GitLab users knowledge to help me understand the differences and test the script on GItLab.
Thank you for the feed back.

**Comment by BradleyA** [comment]
Needs additional testing but initial testing did not display any incidents with script being used with GitLab projects.  Changed help text in script to reflect support with GitLab

**Comment by BradleyA** [comment]
A copy of markit can be found on GitLab at the following URL
https://gitlab.com/BradleyAxe/markit
